### ISSUE TITLE
Possible to make the commit message available in mustache templates?

### ISSUE THREAD

**Issue by nrvale0** [drone-plugins/drone-slack-blame#17]
...would be nice to include the commit message in msg to Slack for additional context.

**Comment by donny-dont** [comment]
@nrvale0 https://github.com/drone/drone-plugin-starter/blob/master/main.go has a list of all the flags we could use. Let me know what you want to add or as always pull requests welcome :wink:

**Comment by nrvale0** [comment]
See "{{commit.messsage}}" here for an example of what it might look like: https://github.com/nrvale0/ui/blob/drone_05/.drone.yml#L25

I made a pass at figuring out how to enable this but I've not had a chance to get familiar w/ golang just yet.

**Comment by donny-dont** [comment]
I was asking if you wanted anything else to be exposed.

I can do the work I just have other work so if you need it right this second then you might want to take a stab. Adding it shouldn't be too hard.

**Comment by nrvale0** [comment]
Oh, I see. No, not a high priority on this end. Just a suggestion for a nice-to-have. At your leisure. 

I can't think of anything else we'd like to have via mustache at this time.
