### ISSUE TITLE
Hyperlink username to GitHub

### ISSUE THREAD

**Issue by nodesocket** [drone-plugins/drone-slack-blame#2]
Just link to the GitHub user page for that user.

**Comment by donny-dont** [comment]
@nodesocket the remote URL is not exposed but I think you can build it out once #5 is fixed.

**Comment by tboerger** [comment]
Don't forget that drone is not only focused on GitHub ;)

**Comment by donny-dont** [comment]
I think this is fixed @nodesocket since templates are there in #10
