### ISSUE TITLE
slack name not retrieving current name of user

### ISSUE THREAD

**Issue by jordan-simonovski** [drone-plugins/drone-slack-blame#27]
The bot is currently trying to tag users by their old handles (likely first handles). An alternative could also be tagging users by their user Ids, and whatever name is picked up to ensure they're always tagged.

IIRC, the syntax bot users can use to tag users is the following:

<@{slackUserId}|{slackUsername}>

**Comment by donny-dont** [comment]
@jordan-simonovski did not know that. Would you like to open a PR?

**Comment by josmo** [comment]
I know this is pretty late, but I think this is because It's using the old depricated slack user name and not the display name off of the profile. I'm trying a fix now and will PR in.

**Comment by donny-dont** [comment]
@josmo thanks! Greatly appreciated!

**Comment by mumoshu** [comment]
@donny-dont @josmo Can we safely close this as resolved, as #40 has been merged? 😃
