### ISSUE TITLE
S3/JSON Name Lookup Support

### ISSUE THREAD

**Issue by KayoticSully** [drone-plugins/drone-slack-blame#31]
@donny-dont I'm opening this as a way to have a start point to work out my PR to the drone-slack plugin (https://github.com/drone-plugins/drone-slack/pull/84)

I have a few questions before I migrate that work over to this project. 

Would a PR for S3 support be welcome? Rather than define a user map string in my drone.yml file I would rather use a mapping that already exists for my team which lives on S3.  I believe in using a single source of truth as much as possible.

For my team, that mapping file is formatted in JSON. Would that be a welcome option for the user mapping here? Not to replace what already exists but just a second accepted format?

**Comment by donny-dont** [comment]
drone-slack-blame has the ability to get the mapping from a single location.

https://github.com/drone-plugins/drone-slack-blame/blob/master/plugin.go#L287-L302

Assuming that there's a URL for your JSON file then this should work out of the box for you.

**Comment by KayoticSully** [comment]
Nice! So I would pass the S3 url as the `mapping` option? Is there a specific format for the JSON file?  We have a simple mapping in the format.

```
{
   "githubName": "slackName",
   ...
}
```

Would this work out of the box? I couldn't find documentation on this if you do have it somewhere. I can dig into the code to find out myself but figured its worth an ask if it could save some time.

**Comment by donny-dont** [comment]
I THINK it was the committers email to the slack username. The mapping was a feature request and not something I actually use personally with this plugin.

**Comment by KayoticSully** [comment]
Okay Ill dig around and experiment with it.  Thanks if this works out of the box Ill be extremely happy.

**Comment by KayoticSully** [comment]
Looks like it can do either email or authorName

```
	if val, ok := mapping[p.Build.Email]; ok {
		logrus.WithFields(logrus.Fields{
			"username": val,
		}).Info("Searching for user by name, using build.email as key")
		search = checkUsername
		find = val
	} else if val, ok := mapping[p.Build.Author]; ok {
		logrus.WithFields(logrus.Fields{
			"username": val,
		}).Info("Searching for user by name, using build.author as key")
		search = checkUsername
		find = val
	} 
```

Awesome! Ill give this a shot.

**Comment by donny-dont** [comment]
@KayoticSully 🤞 that it works for you out of the box

**Comment by KayoticSully** [comment]
This looks to be perfect.  And FWIW I didn't end up needing the mapping after all.  Didn't realize this would use the slack api to look an author up by git email set in the `git config user.email` setting for the project.  We all have that set to our work email at my company so that was sufficient for the translation.

Thanks!

**Comment by donny-dont** [comment]
No problem! If you have any thoughts on documentation let me know. Glad it worked for you. I think this is much nicer for larger orgs. The other nice thing is you can actually have it conditional on branches so if its a feature branch you can just have it hit the author directly and save the shaming for when `master` or `release` is broken 😸

**Comment by KayoticSully** [comment]
@donny-dont  I agree! haha.  
Question about that specifically though.... Is there a way to turn off the private slack messages? The way I have it setup is a separate conditional drone step for different branch types. 

On `feature/*` branches I only pm the author, which works well. 
On `master/develop` I want to only message the channel (because I @author in the message).  If thats not already available I can tweak the message to just mention the author since they already get notified by the PM.  

Just wondering since what I described above is our ideal way to operate. I don't want to ping the author twice.

**Comment by donny-dont** [comment]
I have used yaml variables when doing slack blame. You put the main things you want in there like the template and all that.

```
# Variables
_slack_blame: &SLACK_BLAME
  image: plugins/slack-blame
  success_template: <your template goes here>
  failure_template: <your template goes here>
```

Then the other ones extend that and select based on branch. If channel is empty it'll ping the user directly. If its not then it pings the channel.

```
  # Notifications
  notify_user:
    <<: *SLACK_BLAME
    when:
      status: [failure, changed]
      branch:
        include: "*"
        exclude: master
      
  notify_channel:
    <<: *SLACK_BLAME
    channel: <your channel>
    when:
      status: [failure, changed]
      branch: master
```

Those are from older Drone 0.5 stuff that I have handy so just double check with whatever version you're using.

**Comment by KayoticSully** [comment]
Oh... Okay I have observed when the channel being defined, it pings both the author and the channel.  If that is not supposed to happen then Ill double check my config to see if Im running two steps by accident.
