### ISSUE TITLE
allow storing a github -> slack user mapping

### ISSUE THREAD

**Issue by nlf** [drone-plugins/drone-slack-blame#4]
the majority of my team doesn't have matching emails in github and slack, so it would be nice if we could manually map those.

ideally this would be in the secrets somehow, could just be a simple `github_user=slack_user,github_user2=slack_user2` list which would be easy-ish to put in secrets and expand in the plugin

**Comment by donny-dont** [comment]
@nlf what about a JSON map style format?

**Comment by nlf** [comment]
works for me

**Comment by donny-dont** [comment]
K this will be the behavior in the 0.5 release.
