### ISSUE TITLE
allow variables in messages

### ISSUE THREAD

**Issue by nlf** [drone-plugins/drone-slack-blame#5]
might be nice to expand `$$VARIABLE` style variables in messages, that would allow for super customizable alerts that show as much or as little information as an end user wants

**Comment by khirakawa** [comment]
+1

Drone-slack seems to do something similar https://github.com/drone-plugins/drone-slack/blob/master/DOCS.md#custom-messages

**Comment by donny-dont** [comment]
Currently fixing this in 0.5 branch
