### ISSUE TITLE
Message on build status change

### ISSUE THREAD

**Issue by gabro** [drone-plugins/drone-slack-blame#9]
It'd be nice to send messages when the build status changes, i.e. not sending it for any successful builds but only for the ones that changed it to success after a failing status.

**Comment by tboerger** [comment]
This is already possible, please check the conditions at http://readme.drone.io/usage/notify/#conditions:d1fea7f63b32cc4bab67588d2fde8aa7

**Comment by gabro** [comment]
Oh thank you for the pointer. I missed it as it was in the global plugin documentation.
